spring:
  datasource:
    url: jdbc:mysql://localCentos:3306/guli_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
mybatis-plus:
  global-config:
    db-config:
      id-type: auto